### ISSUE TITLE
Development of the golang r2 components

### ISSUE THREAD

**Issue by chocolatkey** [readium/readium-planning#1]
I noticed in the teams document that there is no assignment for the golang components of r2. Does this mean that their development has been discontinued?

**Comment by rkwright** [comment]
Thanks for your interest.  No, what this indicates is that we haven't closed the loop on who is doing what.  This is an on-going problem with open-source - the resources are not always there when you expect.

All that being said, there is little work being done on the GO versions of the components, but we welcome any and all who like to contribute.

**Comment by chocolatkey** [comment]
@rkwright Thank you for the reply. I'm glad that a golang is still part of the roadmap. I've been (over the past year) been developing somewhat of a streamer, as mentioned in another issue. At the moment it only serves comics (visual narrative) at the moment, but I've started cleaning it up and turning it into a full-fledged streamer will be open sourcing it in the future. Maybe I can contribute to the golang version, having initially taken inspiration from it and the more up-to-date streamers in other languages
